version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: shiftbox-db
    environment:
      POSTGRES_USER: shiftbox
      POSTGRES_PASSWORD: shiftbox123
      POSTGRES_DB: shiftbox_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U shiftbox"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build: ./backend
    container_name: shiftbox-api
    environment:
      DATABASE_URL: postgresql://shiftbox:shiftbox123@db:5432/shiftbox_db
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      db:
        condition: service_healthy
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  postgres_data:

