"""add_queue_position_to_loans

Revision ID: 10f93f5ff6c1
Revises: 936b587f4acd
Create Date: 2025-10-04 18:39:39.051425

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10f93f5ff6c1'
down_revision = '936b587f4acd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('loans', sa.Column('queue_position', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('loans', 'queue_position')
    # ### end Alembic commands ###

