"""add_accrual_fields

Revision ID: 63b99dfd8154
Revises: 7d2ae23afe39
Create Date: 2025-10-05 01:01:50.474656

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63b99dfd8154'
down_revision = '7d2ae23afe39'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('investments', sa.Column('last_accrual_at', sa.DateTime(), nullable=True))
    op.add_column('loans', sa.Column('interest_accrued', sa.Float(), nullable=True))
    op.add_column('loans', sa.Column('last_accrual_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('loans', 'last_accrual_at')
    op.drop_column('loans', 'interest_accrued')
    op.drop_column('investments', 'last_accrual_at')
    # ### end Alembic commands ###

